In [4]:
import pandas as pd
import numpy as np

In [9]:
streaming_df = pd.read_csv(r"C:\Intern season\Spotify-pulse\data\raw\spotify_streaming_history.csv")

behavior_df = pd.read_csv(
    r"C:\Intern season\Spotify-pulse\data\raw\spotify_user_behavior.csv"
)

preferences_df = pd.read_excel(
    r"C:\Intern season\Spotify-pulse\data\raw\spotify_user_preferences.xlsx"
)

In [10]:
print("Streaming History :", streaming_df.shape)
print("User Behavior     :", behavior_df.shape)
print("User Preferences  :", preferences_df.shape)

Streaming History : (149860, 11)
User Behavior     : (8000, 12)
User Preferences  : (520, 20)

In [11]:
display(streaming_df.head())
display(behavior_df.head())
display(preferences_df.head())

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0
2,3,Male,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Female,22,CA,Student,36,2,0.31,Mobile,0,1,0
4,5,Other,29,US,Family,250,57,0.36,Mobile,0,1,1

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating,pod_lis_frequency,fav_pod_genre,preffered_pod_format,pod_host_preference,preffered_pod_duration,pod_variety_satisfaction
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [12]:
def data_quality_report(df, name):
    print("=" * 70)
    print(f"DATA QUALITY REPORT : {name}")
    print("=" * 70)

    print(f"\nShape : {df.shape}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nMemory Usage:")
    print(df.memory_usage(deep=True).sum() / (1024**2), "MB")

In [13]:
data_quality_report(streaming_df, "Streaming History")

======================================================================
DATA QUALITY REPORT : Streaming History
======================================================================

Shape : (149860, 11)

Column Names:
['spotify_track_uri', 'ts', 'platform', 'ms_played', 'track_name', 'artist_name', 'album_name', 'reason_start', 'reason_end', 'shuffle', 'skipped']

Data Types:
spotify_track_uri      str
ts                     str
platform               str
ms_played            int64
track_name             str
artist_name            str
album_name             str
reason_start           str
reason_end             str
shuffle               bool
skipped               bool
dtype: object

Missing Values:
spotify_track_uri      0
ts                     0
platform               0
ms_played              0
track_name             0
artist_name            0
album_name             0
reason_start         143
reason_end           117
shuffle                0
skipped                0
dtype: int64

Duplicate Rows:
1185

Memory Usage:
74.68164348602295 MB

In [14]:
data_quality_report(preferences_df, "User Preferences")

======================================================================
DATA QUALITY REPORT : User Preferences
======================================================================

Shape : (520, 20)

Column Names:
['Age', 'Gender', 'spotify_usage_period', 'spotify_listening_device', 'spotify_subscription_plan', 'premium_sub_willingness', 'preffered_premium_plan', 'preferred_listening_content', 'fav_music_genre', 'music_time_slot', 'music_Influencial_mood', 'music_lis_frequency', 'music_expl_method', 'music_recc_rating', 'pod_lis_frequency', 'fav_pod_genre', 'preffered_pod_format', 'pod_host_preference', 'preffered_pod_duration', 'pod_variety_satisfaction']

Data Types:
Age                              str
Gender                           str
spotify_usage_period             str
spotify_listening_device         str
spotify_subscription_plan        str
premium_sub_willingness          str
preffered_premium_plan           str
preferred_listening_content      str
fav_music_genre                  str
music_time_slot                  str
music_Influencial_mood           str
music_lis_frequency              str
music_expl_method                str
music_recc_rating              int64
pod_lis_frequency                str
fav_pod_genre                    str
preffered_pod_format             str
pod_host_preference              str
preffered_pod_duration           str
pod_variety_satisfaction         str
dtype: object

Missing Values:
Age                              0
Gender                           0
spotify_usage_period             0
spotify_listening_device         0
spotify_subscription_plan        0
premium_sub_willingness          0
preffered_premium_plan         208
preferred_listening_content      0
fav_music_genre                  0
music_time_slot                  0
music_Influencial_mood           0
music_lis_frequency              0
music_expl_method                0
music_recc_rating                0
pod_lis_frequency                0
fav_pod_genre                  148
preffered_pod_format           140
pod_host_preference            141
preffered_pod_duration         129
pod_variety_satisfaction         0
dtype: int64

Duplicate Rows:
1

Memory Usage:
0.5695219039916992 MB

In [15]:
data_quality_report(behavior_df, "User Behavior")

======================================================================
DATA QUALITY REPORT : User Behavior
======================================================================

Shape : (8000, 12)

Column Names:
['user_id', 'gender', 'age', 'country', 'subscription_type', 'listening_time', 'songs_played_per_day', 'skip_rate', 'device_type', 'ads_listened_per_week', 'offline_listening', 'is_churned']

Data Types:
user_id                    int64
gender                       str
age                        int64
country                      str
subscription_type            str
listening_time             int64
songs_played_per_day       int64
skip_rate                float64
device_type                  str
ads_listened_per_week      int64
offline_listening          int64
is_churned                 int64
dtype: object

Missing Values:
user_id                  0
gender                   0
age                      0
country                  0
subscription_type        0
listening_time           0
songs_played_per_day     0
skip_rate                0
device_type              0
ads_listened_per_week    0
offline_listening        0
is_churned               0
dtype: int64

Duplicate Rows:
0

Memory Usage:
2.12387752532959 MB

In [16]:
def missing_value_report(df):
    report = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values,
        "% Missing": (df.isnull().sum()/len(df)*100).round(2).values
    })

    return report.sort_values("% Missing", ascending=False)

In [17]:
missing_value_report(streaming_df)

               Column  Missing Values  % Missing
7        reason_start             143       0.10
8          reason_end             117       0.08
0   spotify_track_uri               0       0.00
2            platform               0       0.00
1                  ts               0       0.00
3           ms_played               0       0.00
4          track_name               0       0.00
6          album_name               0       0.00
5         artist_name               0       0.00
9             shuffle               0       0.00
10            skipped               0       0.00

In [18]:
missing_value_report(behavior_df)

                   Column  Missing Values  % Missing
0                 user_id               0        0.0
1                  gender               0        0.0
2                     age               0        0.0
3                 country               0        0.0
4       subscription_type               0        0.0
5          listening_time               0        0.0
6    songs_played_per_day               0        0.0
7               skip_rate               0        0.0
8             device_type               0        0.0
9   ads_listened_per_week               0        0.0
10      offline_listening               0        0.0
11             is_churned               0        0.0

In [19]:
missing_value_report(preferences_df)

                         Column  Missing Values  % Missing
6        preffered_premium_plan             208      40.00
15                fav_pod_genre             148      28.46
17          pod_host_preference             141      27.12
16         preffered_pod_format             140      26.92
18       preffered_pod_duration             129      24.81
2          spotify_usage_period               0       0.00
1                        Gender               0       0.00
0                           Age               0       0.00
3      spotify_listening_device               0       0.00
4     spotify_subscription_plan               0       0.00
5       premium_sub_willingness               0       0.00
7   preferred_listening_content               0       0.00
11          music_lis_frequency               0       0.00
10       music_Influencial_mood               0       0.00
9               music_time_slot               0       0.00
8               fav_music_genre               0       0.00
14            pod_lis_frequency               0       0.00
13            music_recc_rating               0       0.00
12            music_expl_method               0       0.00
19     pod_variety_satisfaction               0       0.00

In [20]:
def duplicate_report(df):
    duplicates = df.duplicated().sum()

    print(f"Duplicate Rows : {duplicates}")

    if duplicates > 0:
        display(df[df.duplicated()].head())

In [22]:
duplicate_report(streaming_df)

Duplicate Rows : 1185

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
1684,3GGUWP38wpqwwu5njjjUVx,2015-09-10 03:25:39,android,0,Je Danse dans ma Tête,Céline Dion,On ne change pas,clickrow,endplay,True,True
4124,6l9EToqnhtadmJ6qX9DDUl,2016-07-17 22:37:14,android,226240,Craving - Acoustic Version,James Bay,Craving,trackdone,trackdone,True,False
4125,4x8KNLPK3PI7sRWBYoOpFQ,2016-07-17 22:37:14,android,165746,I'm Gonna Find Another You - Acoustic,John Mayer,The Village Sessions,trackdone,trackdone,True,False
4126,4kDTvLhGF29gFsqceuxBSC,2016-07-17 22:37:14,android,261080,Not Today,Imagine Dragons,Me Before You,clickrow,trackdone,False,False
4130,74X1epeRufHckhuX1KFD04,2016-07-17 22:37:14,android,413320,Hallelujah,Jeff Buckley,Grace (Legacy Edition),trackdone,trackdone,False,False

In [23]:
duplicate_report(behavior_df)

Duplicate Rows : 0

In [24]:
duplicate_report(preferences_df)

Duplicate Rows : 1

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating,pod_lis_frequency,fav_pod_genre,preffered_pod_format,pod_host_preference,preffered_pod_duration,pod_variety_satisfaction
194,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,"While Traveling, leisure time",recommendations,4,Never,NaN,NaN,NaN,NaN,Ok

In [25]:
streaming_df[streaming_df.duplicated()].head(10)

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped
1684,3GGUWP38wpqwwu5njjjUVx,2015-09-10 03:25:39,android,0,Je Danse dans ma Tête,Céline Dion,On ne change pas,clickrow,endplay,True,True
4124,6l9EToqnhtadmJ6qX9DDUl,2016-07-17 22:37:14,android,226240,Craving - Acoustic Version,James Bay,Craving,trackdone,trackdone,True,False
4125,4x8KNLPK3PI7sRWBYoOpFQ,2016-07-17 22:37:14,android,165746,I'm Gonna Find Another You - Acoustic,John Mayer,The Village Sessions,trackdone,trackdone,True,False
4126,4kDTvLhGF29gFsqceuxBSC,2016-07-17 22:37:14,android,261080,Not Today,Imagine Dragons,Me Before You,clickrow,trackdone,False,False
4130,74X1epeRufHckhuX1KFD04,2016-07-17 22:37:14,android,413320,Hallelujah,Jeff Buckley,Grace (Legacy Edition),trackdone,trackdone,False,False
4322,3ntrdR24dLkKrzSGRv1FlH,2016-07-30 23:11:42,android,211666,Stand By Me - Remastered 2010,John Lennon,Rock 'N' Roll,clickrow,trackdone,False,False
6432,74X1epeRufHckhuX1KFD04,2016-11-16 02:53:33,android,413320,Hallelujah,Jeff Buckley,Grace (Legacy Edition),trackdone,trackdone,False,False
6433,3RMq7XrI3UtLXZBESe69fk,2016-11-16 02:53:33,android,347133,In Repair - Acoustic,John Mayer,The Village Sessions,trackdone,trackdone,False,False
6434,1yJZwBqTyGTB7mz8nZyiel,2016-11-16 02:53:33,android,188960,Barcelona,George Ezra,Wanted on Voyage,trackdone,trackdone,False,False
6439,4x8KNLPK3PI7sRWBYoOpFQ,2016-11-16 02:53:33,android,165746,I'm Gonna Find Another You - Acoustic,John Mayer,The Village Sessions,trackdone,trackdone,False,False

# Data Cleaning

Cleaning decisions:
- Remove duplicate rows from Streaming History.
- Remove duplicate rows from User Preferences.
- Keep User Behavior unchanged.
- Fill missing values in `reason_start` and `reason_end` with `"unknown"`.
- Preserve structural missing values in the User Preferences dataset.

In [26]:
# -----------------------------
# Remove duplicate rows
# -----------------------------

streaming_df = streaming_df.drop_duplicates()

preferences_df = preferences_df.drop_duplicates()

In [27]:
# -----------------------------
# Fill missing values
# -----------------------------

streaming_df["reason_start"] = streaming_df["reason_start"].fillna("unknown")

streaming_df["reason_end"] = streaming_df["reason_end"].fillna("unknown")

In [28]:
print("Streaming Shape :", streaming_df.shape)
print("Behavior Shape  :", behavior_df.shape)
print("Preferences Shape :", preferences_df.shape)

print("\nMissing Values in Streaming")
print(streaming_df[["reason_start","reason_end"]].isnull().sum())

print("\nDuplicate Rows")
print(streaming_df.duplicated().sum())
print(behavior_df.duplicated().sum())
print(preferences_df.duplicated().sum())

Streaming Shape : (148675, 11)
Behavior Shape  : (8000, 12)
Preferences Shape : (519, 20)

Missing Values in Streaming
reason_start    0
reason_end      0
dtype: int64

Duplicate Rows
0
0
0

In [29]:
# ---------------------------------------
# Create Tracks Dimension Table
# ---------------------------------------

tracks_df = streaming_df[
    ["spotify_track_uri", "track_name", "artist_name", "album_name"]
].drop_duplicates().reset_index(drop=True)

In [30]:
tracks_df.insert(
    0,
    "track_id",
    range(1, len(tracks_df) + 1)
)

In [31]:
tracks_df.head()

,track_id,spotify_track_uri,track_name,artist_name,album_name
0,1,2J3n32GeLmMjwuAzyhcSNe,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn
1,2,1oHxIPqJyvAYHy0PVrDU98,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months
2,3,487OPlneJNni3NWC8SYqhW,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition
3,4,5IyblF777jLZj1vGHG2UD3,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition
4,5,0GgAAB0ZMllFhbNc3mAodO,Half Mast,Empire Of The Sun,Walking On A Dream

In [32]:
print("Number of Unique Tracks :", len(tracks_df))

Number of Unique Tracks : 16597

In [33]:
tracks_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16597 entries, 0 to 16596
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   track_id           16597 non-null  int64
 1   spotify_track_uri  16597 non-null  str
 2   track_name         16597 non-null  str
 3   artist_name        16597 non-null  str
 4   album_name         16597 non-null  str
dtypes: int64(1), str(4)
memory usage: 648.4 KB

In [36]:
tracks_df.to_csv(
    r"C:\Intern season\Spotify-pulse\data\processed\tracks.csv",
    index=False
)

In [37]:
streaming_events_df = streaming_df.copy()

In [38]:
streaming_events_df = streaming_events_df.merge(
    tracks_df,
    on=[
        "spotify_track_uri",
        "track_name",
        "artist_name",
        "album_name"
    ],
    how="left"
)

In [39]:
streaming_events_df.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,track_id
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,clickrow,False,False,1
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,2
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,unknown,False,False,3
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,clickrow,False,False,4
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,nextbtn,False,False,5

In [40]:
# ---------------------------------------
# Remove redundant track information
# ---------------------------------------

streaming_events_df = streaming_events_df.drop(
    columns=[
        "spotify_track_uri",
        "track_name",
        "artist_name",
        "album_name"
    ]
)

In [41]:
streaming_events_df.head()

,ts,platform,ms_played,reason_start,reason_end,shuffle,skipped,track_id
0,2013-07-08 02:44:34,web player,3185,autoplay,clickrow,False,False,1
1,2013-07-08 02:45:37,web player,61865,clickrow,clickrow,False,False,2
2,2013-07-08 02:50:24,web player,285386,clickrow,unknown,False,False,3
3,2013-07-08 02:52:40,web player,134022,trackdone,clickrow,False,False,4
4,2013-07-08 03:17:52,web player,0,clickrow,nextbtn,False,False,5

In [42]:
streaming_events_df.insert(
    0,
    "stream_id",
    range(1, len(streaming_events_df) + 1)
)

In [43]:
streaming_events_df.head()

,stream_id,ts,platform,ms_played,reason_start,reason_end,shuffle,skipped,track_id
0,1,2013-07-08 02:44:34,web player,3185,autoplay,clickrow,False,False,1
1,2,2013-07-08 02:45:37,web player,61865,clickrow,clickrow,False,False,2
2,3,2013-07-08 02:50:24,web player,285386,clickrow,unknown,False,False,3
3,4,2013-07-08 02:52:40,web player,134022,trackdone,clickrow,False,False,4
4,5,2013-07-08 03:17:52,web player,0,clickrow,nextbtn,False,False,5

In [44]:
streaming_events_df.to_csv(
    r"C:\Intern season\Spotify-pulse\data\processed\streaming_events.csv",
    index=False
)

In [45]:
# ---------------------------------------
# Create Users Dimension Table
# ---------------------------------------

users_df = behavior_df[
    ["user_id", "age", "gender", "country"]
].copy()

In [46]:
users_df.head()

   user_id  age  gender country
0        1   54  Female      CA
1        2   33   Other      DE
2        3   38    Male      AU
3        4   22  Female      CA
4        5   29   Other      US

In [47]:
users_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  8000 non-null   int64
 1   age      8000 non-null   int64
 2   gender   8000 non-null   str
 3   country  8000 non-null   str
dtypes: int64(2), str(2)
memory usage: 250.1 KB

In [48]:
users_df.to_csv(
    r"C:\Intern season\Spotify-pulse\data\processed\users.csv",
    index=False
)

In [49]:
# ---------------------------------------
# Create User Behavior Table
# ---------------------------------------

user_behavior_df = behavior_df[
    [
        "user_id",
        "subscription_type",
        "listening_time",
        "songs_played_per_day",
        "skip_rate",
        "device_type",
        "ads_listened_per_week",
        "offline_listening",
        "is_churned"
    ]
].copy()

In [50]:
user_behavior_df.head()

,user_id,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Free,26,23,0.20,Desktop,31,0,1
1,2,Family,141,62,0.34,Web,0,1,0
2,3,Premium,199,38,0.04,Mobile,0,1,1
3,4,Student,36,2,0.31,Mobile,0,1,0
4,5,Family,250,57,0.36,Mobile,0,1,1

In [51]:
user_behavior_df.to_csv(
    r"C:\Intern season\Spotify-pulse\data\processed\user_behavior.csv",
    index=False
)

In [52]:
user_preferences_df = preferences_df.copy()